### PR TITLE
pos-print: retry database connection on startup

### LINKED ISSUE #17: pos-print: retry database connection on startup
PosPrintService should retry to connect to database multiple times on startup, if it fails to connect the startup process needs to be terminated. This will ensure that everything with the database is Ok and is running fine.

### PR DESCRIPTION
**Pull request by gadjevb**
PosPrintService will now retry to connect to database multiple times on startup with 2 seconds intervals, if fails to connect process is terminated.

Fixes #17 

Here a picture of the process:
unavailable

### CODE REVIEW

File: pos-print/src/main/java/com/clouway/pos/print/adapter/http/HttpBackend.java [hunk 1]
```diff
@@ -76,4 +71,41 @@ public void stop() throws Exception {
     server.stop();
   }
 
+  private MongoClient establishMongoDbConnection(List<String> hosts) {
```
Comment (mgenov) [inline pos-print/src/main/java/com/clouway/pos/print/adapter/http/HttpBackend.java]: It may be established in main instead of here. 

It's not a good idea persistence logic to go in the HttpBackend class. Also the CommandCLI will be removed as dependency as DB related params are not going to be required anymore and just port could be passed directly to the HttpBackend.

**Comment by gadjevb** [comment]
@mgenov made the required changes.
